builtinEnter: Object.create / 4
builtinExit: Object.create / 6
builtinEnter: Object.create / 4
builtinExit: Object.create / 6
functionExit: (src/ch.usi.inf.nodeprof.test/js/minitests/exitException.js:1:1:60:4) / 3
functionEnter: foo / (src/ch.usi.inf.nodeprof.test/js/minitests/exitException.js:18:1:20:2) / 4
functionExit with exception "this is an exception(string)": (src/ch.usi.inf.nodeprof.test/js/minitests/exitException.js:18:1:20:2) / 3
exception: this is an exception
functionExit with exception "Error: this is an error(object)": (src/ch.usi.inf.nodeprof.test/js/minitests/exitException.js:22:1:24:2) / 3
exception: Error: this is an error
functionExit with exception "undefined(undefined)": (src/ch.usi.inf.nodeprof.test/js/minitests/exitException.js:26:1:28:2) / 3
exception: undefined
return (src/ch.usi.inf.nodeprof.test/js/minitests/exitException.js:53:4:53:14) val returns 42
return (src/ch.usi.inf.nodeprof.test/js/minitests/exitException.js:55:4:55:14) val returns 43
functionExit: (src/ch.usi.inf.nodeprof.test/js/minitests/exitException.js:48:2:58:2) / 3
functionExit: (src/ch.usi.inf.nodeprof.test/js/minitests/exitException.js:48:2:58:2) / returnVal (number): 43
functionExit: (src/ch.usi.inf.nodeprof.test/js/minitests/exitException.js:1:2:60:2) / 3
[ 'Object.create', 'foo' ]
